# This workflow will build and publish a new version of the documentation.
# It is supposed to be run only when the release is published.

name: Publish documentation

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
      - uses: taiki-e/install-action@just
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Configure git credentials
        uses: fregante/setup-git-user@v2
      - name: Build and deploy
        run: |
          just build-docs ${{ github.ref_name }}
